-- -----------------------------------------------------
-- SCHEMA SISTEMALAVAGEM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SISTEMALAVAGEM` DEFAULT CHARACTER SET UTF8 ;
USE `SISTEMALAVAGEM` ;

-- -----------------------------------------------------
-- TABLE CLIENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISTEMALAVAGEM`.`CLIENTE` (
  `CLI_ID_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `CLI_NOME` VARCHAR(50) NULL,
  `CLI_ENDERECO` VARCHAR(150) NULL,
  `CLI_TELEFONE` VARCHAR(20) NULL,
  `CLI_EMAIL` VARCHAR(64) NULL,
  `CLI_CPF` VARCHAR(11) NULL,
  PRIMARY KEY (`CLI_ID_CLIENTE`),
  UNIQUE INDEX `CLI_CPF_UNIQUE` (`CLI_CPF` ASC) VISIBLE
) ENGINE = INNODB;

-- -----------------------------------------------------
-- TABLE VEICULO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISTEMALAVAGEM`.`VEICULO` (
  `VEI_ID_VEICULO` INT NOT NULL AUTO_INCREMENT,
  `VEI_ID_CLIENTE` INT NOT NULL,
  `VEI_MARCA` VARCHAR(45) NULL,
  `VEI_MODELO` VARCHAR(45) NULL,
  `VEI_COR` VARCHAR(45) NULL,
  `VEI_PLACA` VARCHAR(15) NULL,
  PRIMARY KEY (`VEI_ID_VEICULO`),
  INDEX `FK_VEICULO_CLIENTE_IDX` (`VEI_ID_CLIENTE` ASC) VISIBLE,
  UNIQUE INDEX `VEI_PLACA_UNIQUE` (`VEI_PLACA` ASC) VISIBLE,
  CONSTRAINT `FK_VEICULO_CLIENTE`
    FOREIGN KEY (`VEI_ID_CLIENTE`)
    REFERENCES `SISTEMALAVAGEM`.`CLIENTE` (`CLI_ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = INNODB;

-- -----------------------------------------------------
-- TABLE TIPO_SERVICO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISTEMALAVAGEM`.`TIPO_SERVICO` (
  `TS_ID_TIPO_SERVICO` INT NOT NULL AUTO_INCREMENT,
  `TS_NOME` VARCHAR(45) NULL,
  `TS_PRECO` DECIMAL(10,2) NULL,
  PRIMARY KEY (`TS_ID_TIPO_SERVICO`)
) ENGINE = INNODB;

-- -----------------------------------------------------
-- TABLE RESPONSAVEL
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISTEMALAVAGEM`.`RESPONSAVEL` (
  `RES_ID_RESPONSAVEL` INT NOT NULL AUTO_INCREMENT,
  `RES_NOME` VARCHAR(50) NULL,
  `RES_TELEFONE` VARCHAR(20) NULL,
  `RES_CPF` VARCHAR(11) NULL,
  `RES_SENHA` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`RES_ID_RESPONSAVEL`),
  UNIQUE INDEX `RES_CPF_UNIQUE` (`RES_CPF` ASC) VISIBLE
) ENGINE = INNODB;

-- -----------------------------------------------------
-- TABLE SERVICO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISTEMALAVAGEM`.`SERVICO` (
  `SER_ID_SERVICO` INT NOT NULL AUTO_INCREMENT,
  `SER_DATA` DATE NULL,
  `SER_ID_TIPO_SERVICO` INT NOT NULL,
  `SER_ID_VEICULO` INT NOT NULL,
  `SER_ID_RESPONSAVEL` INT NOT NULL,
  PRIMARY KEY (`SER_ID_SERVICO`),
  INDEX `FK_SERVICO_TIPO_SERVICO_IDX` (`SER_ID_TIPO_SERVICO` ASC) VISIBLE,
  INDEX `FK_SERVICO_VEICULO_IDX` (`SER_ID_VEICULO` ASC) VISIBLE,
  INDEX `FK_SERVICO_RESPONSAVEL_IDX` (`SER_ID_RESPONSAVEL` ASC) VISIBLE,
  CONSTRAINT `FK_SERVICO_TIPO_SERVICO`
    FOREIGN KEY (`SER_ID_TIPO_SERVICO`)
    REFERENCES `SISTEMALAVAGEM`.`TIPO_SERVICO` (`TS_ID_TIPO_SERVICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SERVICO_VEICULO`
    FOREIGN KEY (`SER_ID_VEICULO`)
    REFERENCES `SISTEMALAVAGEM`.`VEICULO` (`VEI_ID_VEICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SERVICO_RESPONSAVEL`
    FOREIGN KEY (`SER_ID_RESPONSAVEL`)
    REFERENCES `SISTEMALAVAGEM`.`RESPONSAVEL` (`RES_ID_RESPONSAVEL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = INNODB;

-- -----------------------------------------------------
-- TABLE AGENDAMENTO_SERVICO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISTEMALAVAGEM`.`AGENDAMENTO_SERVICO` (
  `AG_ID_AGENDAMENTO` INT NOT NULL AUTO_INCREMENT,
  `AG_DATA` DATE NOT NULL,
  `AG_HORA` TIME NOT NULL,
  `AG_ID_VEICULO` INT NOT NULL,
  `AG_ID_TIPO_SERVICO` INT NOT NULL,
  `AG_STATUS` VARCHAR(1) NOT NULL DEFAULT 'P', -- P = PENDENTE, C = CONFIRMADO, X = CANCELADO
  PRIMARY KEY (`AG_ID_AGENDAMENTO`),
  INDEX `FK_AGENDAMENTO_VEICULO_IDX` (`AG_ID_VEICULO` ASC) VISIBLE,
  INDEX `FK_AGENDAMENTO_TIPO_SERVICO_IDX` (`AG_ID_TIPO_SERVICO` ASC) VISIBLE,
  CONSTRAINT `FK_AGENDAMENTO_VEICULO`
    FOREIGN KEY (`AG_ID_VEICULO`)
    REFERENCES `SISTEMALAVAGEM`.`VEICULO` (`VEI_ID_VEICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AGENDAMENTO_TIPO_SERVICO`
    FOREIGN KEY (`AG_ID_TIPO_SERVICO`)
    REFERENCES `SISTEMALAVAGEM`.`TIPO_SERVICO` (`TS_ID_TIPO_SERVICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = INNODB;
